### ISSUE TITLE
contextily dependency is missing from requirements.txt

### ISSUE THREAD

**Issue by zpeleg** [amirkl91/ClusterOn#3]
App fails to start without it.

```
Matplotlib is building the font cache; this may take a moment.
2024-09-30 20:09:24.990 Uncaught app exception
Traceback (most recent call last):
  File "/Users/ziv/.pyenv/versions/3.12.5/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/Users/ziv/.pyenv/versions/3.12.5/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "/Users/ziv/Code/ClusterOn/app/streamlit_app.py", line 7, in <module>
    import contextily as ctx
ModuleNotFoundError: No module named 'contextily'
```

**Comment by zpeleg** [comment]
Also got an error that `mapclassify` is missing when I tried to export a zip but stuff keeps working for now...

**Comment by amirkl91** [comment]
I fixed the requirements, so contextily should be.


From: zpeleg ***@***.***>
Date: Monday, 30 September 2024 at 20:22
To: amirkl91/ClusterOn ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [amirkl91/ClusterOn] contextily dependency is missing from requirements.txt (Issue #3)
Caution: External Sender. Do not click on links or open attachments unless you recognize the sender.


Also got an error that mapclassify is missing when I tried to export a zip but stuff keeps working for now...
